
Vagrant.configure("2") do |config|

  # --------------------------------- Machine Config ----------------------------------
  proxy_conf = "proxym300.conf"
  mysql_password = "m300mysql-Yannick"

  # Box OS Setting
  config.vm.box = "ubuntu/xenial64"

  # Machine Settings
  config.vm.hostname = "yannicks-machine"

  # Network Settings
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true

  # Folder Sync
  config.vm.synced_folder ".", "/var/www/html/", create: true

  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "512" 
  end

  # Shell Commands
  config.vm.provision "shell", inline: <<-SHELL

  # Get the latest updates
  sudo apt-get update


  # --------------------------------- Firewall Config ----------------------------------
  # Install the service, firewall and proxy
  sudo apt-get install apache2 -y
  sudo apt-get install ufw -y

  ## Firewall Rules, Settigs
  sudo ufw deny out to any
  sudo ufw allow from any to any port 22
  sudo ufw allow from any to any port 80
  sudo ufw allow from any to any port 443
  sudo ufw enable


  # ---------------------------------- Proxy Config ------------------------------------
  # Install the Modules
  sudo apt-get install libapache2-mod-proxy-html
  sudo apt-get install libxml2-dev -y

  # Activate modules for proxy
  sudo a2enmod proxy
  sudo a2enmod proxy_html
  sudo a2enmod proxy_http

  #Proxy Config
  echo "echo '<VirtualHost *:80>' >> /etc/apache2/sites-available/#{proxy_conf}" | sudo bash
  echo "echo '	ServerName mysql-m300' >> /etc/apache2/sites-available/#{proxy_conf}" | sudo bash
  echo "echo '	ServerAlias www.mysql-m300 '>> /etc/apache2/sites-available/#{proxy_conf}" | sudo bash
  echo "echo '</VirtualHost>' >> /etc/apache2/sites-available/#{proxy_conf}" | sudo bash
  
  sudo a2ensite /etc/apache2/sites-available/#{proxy_conf}
  

  # --------------------------------- Groups and Rules ----------------------------------
  #Gruppenordner erstellen
  mkdir -p /grp/database
  mkdir -p /grp/webserver

  #Benutzer hinzufügen
  useradd dbadmin -p password
  useradd webadmin -p password

  #Gruppe Hinzufügen
  groupadd database
  groupadd webserver

  #Benutzer der Gruppe hinzufügen
  usermod -aG database  dbadmin
  usermod -aG webserver webadmin
  
  #Gruppenorder Zugriff erstellen
  chmod 770 /grp/database -R
  chown root:database /grp/database/ -R
  chmod 770 /grp/webserver -R
  chown root:webserver /grp/webserver/ -R


  # -------------------------------- LDAP CONFIG ---------------------------------------
  # LDAP Installation
  sudo apt-get -y install debconf-utils apache2 nmap
  sudo a2enmod cgi  
  sudo a2enmod ldap 
  sudo a2enmod authnz_ldap

  # LDAP Konfigurieren
  sudo mkdir -p  /var/www/html/data && sudo chown www-data:www-data /var/www/html/data 
  export DEBIAN_FRONTEND=noninteractive
  sudo debconf-set-selections <<<'slapd slapd/internal/generated_adminpw password admin'
  sudo debconf-set-selections <<<'slapd slapd/password2 password admin'
  sudo debconf-set-selections <<<'slapd slapd/internal/adminpw password admin'
  sudo debconf-set-selections <<<'slapd slapd/password1 password admin'
  sudo apt-get install -y slapd ldap-utils phpldapadmin
  sudo sed -i -e's/dc=example,dc=com/dc=nodomain/' /etc/phpldapadmin/config.php


  # ------------------------------ Activate HTTPS CONFIG -------------------------------
  sudo ufw allow from any to any port 443
  sudo a2ensite default-ssl.conf
  sudo a2enmod ssl
  sudo a2dissite 000-default.conf
  
  # --------------------------------- Restart the Service -------------------------------
  # Restart the Service
  sudo service apache2 restart


SHELL
end